const ConfigApp = {
  backendUrl: 'http://localhost:3002',
};

export const CardValue = [
  { card: '0C', value: '10' },
  { card: '0S', value: '10' },
  { card: '2H', value: '2' },
  { card: '3D', value: '3' },
  { card: '4C', value: '4' },
  { card: '4S', value: '4' },
  { card: '5H', value: '5' },
  { card: '6D', value: '6' },
  { card: '7C', value: '7' },
  { card: '7S', value: '7' },
  { card: '8H', value: '8' },
  { card: '9D', value: '9' },
  { card: 'AC', value: 'A' },
  { card: 'AS', value: 'A' },
  { card: 'JH', value: '10' },
  { card: 'KD', value: '10' },
  { card: 'QC', value: '10' },
  { card: 'QS', value: '10' },
  { card: '0D', value: '10' },
  { card: '2C', value: '2' },
  { card: '2S', value: '2' },
  { card: '3H', value: '3' },
  { card: '4D', value: '4' },
  { card: '5C', value: '5' },
  { card: '5S', value: '5' },
  { card: '6H', value: '6' },
  { card: '7D', value: '7' },
  { card: '8C', value: '8' },
  { card: '8S', value: '8' },
  { card: '9H', value: '9' },
  { card: 'AD', value: 'A' },
  { card: 'JC', value: '10' },
  { card: 'JS', value: '10' },
  { card: 'KH', value: '10' },
  { card: 'QD', value: '10' },
  { card: '0H', value: '10' },
  { card: '2D', value: '2' },
  { card: '3C', value: '3' },
  { card: '3S', value: '3' },
  { card: '4H', value: '4' },
  { card: '5D', value: '5' },
  { card: '6C', value: '6' },
  { card: '6S', value: '6' },
  { card: '7H', value: '7' },
  { card: '8D', value: '8' },
  { card: '9C', value: '9' },
  { card: '9S', value: '9' },
  { card: 'AH', value: 'A' },
  { card: 'JD', value: '10' },
  { card: 'KC', value: '10' },
  { card: 'KS', value: '10' },
  { card: 'QH', value: '10' },
];

export default ConfigApp;
